#单数据源
spring:
  datasource:
      name: test
      url: jdbc:mysql://rm-wz9sy13a78dq73z73o.mysql.rds.aliyuncs.com:3306/fnwtv?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: Java2018
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

#mybatis配置
mybatis:
  typeAliasesPackage: com.api.model
  mapper-locations: classpath:mapper/*.xml